import { GridColumn } from './../../shared/components/models/grid-column';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'aco-members',
  templateUrl: './members.component.html',
  styleUrls: ['./members.component.scss']
})
export class MembersComponent implements OnInit {
  memberColumns: any = ['Member Id', 'Name', 'Health Plan', 'Benefit Code', 'Benefit From', 'Benefit Thru', 'PCP Name', 'PCP  From', 'PCP To'];
  gridColumns:GridColumn[]=[

    { field:'memberid', display:'Member Id' },
    { field:'lastName', display:'Member  Name' },
    { field:'healthPlanName', display:'Health Plan' },
    { field:'createdInPayorSystemOn', display:'DOR', filter:'date' },
    { field:'earliestServiceDate', display:'DOC' },
    { field:'paidOn', display:'DOS' },

  ]
  membersData: any = [{
    benefitHistorys: null,
    benefitOptionActiveDate: "2019-01-01T00:00:00",
    benefitOptionCode: "CAHMSR0A",
    benefitOptionExpiryDate: null,
    benefitOptionName: "CA ANTHEM MEDIBLUE PLUS (HMO) - RISK",
    currentPage: 1,
    dwid: 161,
    firstName: null,
    healthPlanName: "ANTHEM MEDICARE",
    lastName: "ANTHEM MCR",
    memberPcpFromDate: "2019-01-01T00:00:00",
    memberPcpToDate: null,
    memberRecUid: "B3A658E0-F432-44F3-8A5A-C0A7479EC11E",
    memberid: "ABMCR01",
    pageSize: 10,
    pcpHistorys: null,
    primaryCareProviderName: "Default Pcp, ",
    primaryCareProviderRecUid: "950C27AE-F19C-4DDE-854C-E7F79D05CD86",
    sortBy: null,
    sortDirection: null
  },
  {
    benefitHistorys: null,
    benefitOptionActiveDate: "2019-01-01T00:00:00",
    benefitOptionCode: "CAHMSR0A",
    benefitOptionExpiryDate: null,
    benefitOptionName: "CA ANTHEM MEDIBLUE PLUS (HMO) - RISK",
    currentPage: 1,
    dwid: 161,
    firstName: null,
    healthPlanName: "ANTHEM MEDICARE",
    lastName: "ANTHEM MCR",
    memberPcpFromDate: "2019-01-01T00:00:00",
    memberPcpToDate: null,
    memberRecUid: "B3A658E0-F432-44F3-8A5A-C0A7479EC11E",
    memberid: "ABMCR01",
    pageSize: 10,
    pcpHistorys: null,
    primaryCareProviderName: "Default Pcp, ",
    primaryCareProviderRecUid: "950C27AE-F19C-4DDE-854C-E7F79D05CD86",
    sortBy: null,
    sortDirection: null
  }
    ,
    {
      benefitHistorys: null,
      benefitOptionActiveDate: "2019-01-01T00:00:00",
      benefitOptionCode: "CAHMSR0A",
      benefitOptionExpiryDate: null,
      benefitOptionName: "CA ANTHEM MEDIBLUE PLUS (HMO) - RISK",
      currentPage: 1,
      dwid: 161,
      firstName: null,
      healthPlanName: "ANTHEM MEDICARE",
      lastName: "ANTHEM MCR",
      memberPcpFromDate: "2019-01-01T00:00:00",
      memberPcpToDate: null,
      memberRecUid: "B3A658E0-F432-44F3-8A5A-C0A7479EC11E",
      memberid: "ABMCR01",
      pageSize: 10,
      pcpHistorys: null,
      primaryCareProviderName: "Default Pcp, ",
      primaryCareProviderRecUid: "950C27AE-F19C-4DDE-854C-E7F79D05CD86",
      sortBy: null,
      sortDirection: null
    }
    ,
    {
      benefitHistorys: null,
      benefitOptionActiveDate: "2019-01-01T00:00:00",
      benefitOptionCode: "CAHMSR0A",
      benefitOptionExpiryDate: null,
      benefitOptionName: "CA ANTHEM MEDIBLUE PLUS (HMO) - RISK",
      currentPage: 1,
      dwid: 161,
      firstName: null,
      healthPlanName: "ANTHEM MEDICARE",
      lastName: "ANTHEM MCR",
      memberPcpFromDate: "2019-01-01T00:00:00",
      memberPcpToDate: null,
      memberRecUid: "B3A658E0-F432-44F3-8A5A-C0A7479EC11E",
      memberid: "ABMCR01",
      pageSize: 10,
      pcpHistorys: null,
      primaryCareProviderName: "Default Pcp, ",
      primaryCareProviderRecUid: "950C27AE-F19C-4DDE-854C-E7F79D05CD86",
      sortBy: null,
      sortDirection: null
    },
  {
    benefitHistorys: null,
    benefitOptionActiveDate: "2019-01-01T00:00:00",
    benefitOptionCode: "CAHMSR0A",
    benefitOptionExpiryDate: null,
    benefitOptionName: "CA ANTHEM MEDIBLUE PLUS (HMO) - RISK",
    currentPage: 1,
    dwid: 161,
    firstName: null,
    healthPlanName: "ANTHEM MEDICARE",
    lastName: "ANTHEM MCR",
    memberPcpFromDate: "2019-01-01T00:00:00",
    memberPcpToDate: null,
    memberRecUid: "B3A658E0-F432-44F3-8A5A-C0A7479EC11E",
    memberid: "ABMCR01",
    pageSize: 10,
    pcpHistorys: null,
    primaryCareProviderName: "Default Pcp, ",
    primaryCareProviderRecUid: "950C27AE-F19C-4DDE-854C-E7F79D05CD86",
    sortBy: null,
    sortDirection: null
  }
    ,
    {
      benefitHistorys: null,
      benefitOptionActiveDate: "2019-01-01T00:00:00",
      benefitOptionCode: "CAHMSR0A",
      benefitOptionExpiryDate: null,
      benefitOptionName: "CA ANTHEM MEDIBLUE PLUS (HMO) - RISK",
      currentPage: 1,
      dwid: 161,
      firstName: null,
      healthPlanName: "ANTHEM MEDICARE",
      lastName: "ANTHEM MCR",
      memberPcpFromDate: "2019-01-01T00:00:00",
      memberPcpToDate: null,
      memberRecUid: "B3A658E0-F432-44F3-8A5A-C0A7479EC11E",
      memberid: "ABMCR01",
      pageSize: 10,
      pcpHistorys: null,
      primaryCareProviderName: "Default Pcp, ",
      primaryCareProviderRecUid: "950C27AE-F19C-4DDE-854C-E7F79D05CD86",
      sortBy: null,
      sortDirection: null
    },
      {
        benefitHistorys: null,
        benefitOptionActiveDate: "2019-01-01T00:00:00",
        benefitOptionCode: "CAHMSR0A",
        benefitOptionExpiryDate: null,
        benefitOptionName: "CA ANTHEM MEDIBLUE PLUS (HMO) - RISK",
        currentPage: 1,
        dwid: 161,
        firstName: null,
        healthPlanName: "ANTHEM MEDICARE",
        lastName: "ANTHEM MCR",
        memberPcpFromDate: "2019-01-01T00:00:00",
        memberPcpToDate: null,
        memberRecUid: "B3A658E0-F432-44F3-8A5A-C0A7479EC11E",
        memberid: "ABMCR01",
        pageSize: 10,
        pcpHistorys: null,
        primaryCareProviderName: "Default Pcp, ",
        primaryCareProviderRecUid: "950C27AE-F19C-4DDE-854C-E7F79D05CD86",
        sortBy: null,
        sortDirection: null
      },
      {
        benefitHistorys: null,
        benefitOptionActiveDate: "2019-01-01T00:00:00",
        benefitOptionCode: "CAHMSR0A",
        benefitOptionExpiryDate: null,
        benefitOptionName: "CA ANTHEM MEDIBLUE PLUS (HMO) - RISK",
        currentPage: 1,
        dwid: 161,
        firstName: null,
        healthPlanName: "ANTHEM MEDICARE",
        lastName: "ANTHEM MCR",
        memberPcpFromDate: "2019-01-01T00:00:00",
        memberPcpToDate: null,
        memberRecUid: "B3A658E0-F432-44F3-8A5A-C0A7479EC11E",
        memberid: "ABMCR01",
        pageSize: 10,
        pcpHistorys: null,
        primaryCareProviderName: "Default Pcp, ",
        primaryCareProviderRecUid: "950C27AE-F19C-4DDE-854C-E7F79D05CD86",
        sortBy: null,
        sortDirection: null
      }
    ,
    {
      benefitHistorys: null,
      benefitOptionActiveDate: "2019-01-01T00:00:00",
      benefitOptionCode: "CAHMSR0A",
      benefitOptionExpiryDate: null,
      benefitOptionName: "CA ANTHEM MEDIBLUE PLUS (HMO) - RISK",
      currentPage: 1,
      dwid: 161,
      firstName: null,
      healthPlanName: "ANTHEM MEDICARE",
      lastName: "ANTHEM MCR",
      memberPcpFromDate: "2019-01-01T00:00:00",
      memberPcpToDate: null,
      memberRecUid: "B3A658E0-F432-44F3-8A5A-C0A7479EC11E",
      memberid: "ABMCR01",
      pageSize: 10,
      pcpHistorys: null,
      primaryCareProviderName: "Default Pcp, ",
      primaryCareProviderRecUid: "950C27AE-F19C-4DDE-854C-E7F79D05CD86",
      sortBy: null,
      sortDirection: null
    }]

  constructor() { }

  ngOnInit() {
  }

}
